cloudinary.api-key=746352737686838
cloudinary.api-secret=awcCLODzZcUhgUuXCpFgB158q6I
cloudinary.cloud-name=dyrveeosj
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.password=shizadon2005
spring.datasource.url=jdbc:mysql://localhost:3306/hobby
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.jpa.hibernate.use-new-id-generator-mappings=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.mvc.hiddenmethod.enabled=true
spring.rsocket.server.port=8080
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nguyendinhquocdeptrai2k5@gmail.com
spring.mail.password=jqlx zysf ocwu xykn
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8
spring.mail.test-connection=false
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.groups-order=DESC
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.disable-swagger-default-url=true
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.amqp.deserialization.trust.all=false
spring.rabbitmq.listener.simple.default-requeue-rejected=false
spring.rabbitmq.listener.simple.trusted-packages=java.util,java.lang,backend.hobbiebackend
jwt.secret=bXlTdXBlclNlY3JldEtleUZvckpXVFRva2VuMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=

# ===== Circuit Breaker =====
resilience4j.circuitbreaker.instances.cloudinaryDelete.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.cloudinaryDelete.sliding-window-size=20
resilience4j.circuitbreaker.instances.cloudinaryDelete.minimum-number-of-calls=10
resilience4j.circuitbreaker.instances.cloudinaryDelete.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.cloudinaryDelete.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.cloudinaryDelete.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.cloudinaryDelete.record-exceptions=java.io.IOException,java.net.SocketTimeoutException,java.util.concurrent.TimeoutException,org.springframework.web.client.ResourceAccessException


resilience4j.timelimiter.instances.cloudinaryDelete.timeout-duration=3s


management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers
management.endpoint.health.show-details=always
